name: Deploy to Azure Spring Apps using passwordless connections

on:
  push:
    branches:
      - ja_JP
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AZCLI_VER: 2.48.1
  # ==== APPS ====:
  API_GATEWAY: api-gateway
  ADMIN_SERVER: admin-server
  CUSTOMERS_SERVICE: customers-service
  VETS_SERVICE: vets-service
  VISITS_SERVICE: visits-service
  # ==== TARGETS ====:
  API_GATEWAY_TGT: spring-petclinic-api-gateway
  ADMIN_SERVER_TGT: spring-petclinic-admin-server
  CUSTOMERS_SERVICE_TGT: spring-petclinic-customers-service
  VETS_SERVICE_TGT: spring-petclinic-vets-service
  VISITS_SERVICE_TGT: spring-petclinic-visits-service/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Azure CLI Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - name: Checkout your repo
      uses: actions/checkout@v3

    - name: Deploy api-gateway
      uses: azure/CLI@v1
      with:
        azcliversion: ${{ env.AZCLI_VER }}
        inlineScript: |
          az config set extension.use_dynamic_install=yes_without_prompt
          az spring app deploy \
                  --resource-group ${{ secrets.RESOURCE_GROUP }} \
                  --service ${{ secrets.SPRING_APPS_SERVICE_NAME }} \
                  --name ${{ env.API_GATEWAY }} \
                  --source-path ${{ github.workspace }} \
                  --jvm-options="-XX:+UseG1GC -XX:+UseStringDeduplication -XX:InitialRAMPercentage=50.0 -XX:MinRAMPercentage=66.6 -XX:MaxRAMPercentage=66.6 -XX:ActiveProcessorCount=1" \
                  --env SPRING_PROFILES_ACTIVE=passwordless BP_JVM_VERSION=17 \
                  --target-module ${{ env.API_GATEWAY_TGT }}

    - name: Deploy admin-server
      uses: azure/CLI@v1
      with:
        azcliversion: ${{ env.AZCLI_VER }}
        inlineScript: |
          az config set extension.use_dynamic_install=yes_without_prompt
          az spring app deploy \
                  --resource-group ${{ secrets.RESOURCE_GROUP }} \
                  --service ${{ secrets.SPRING_APPS_SERVICE_NAME }} \
                  --name ${{ env.ADMIN_SERVER }} \
                  --source-path ${{ github.workspace }} \
                  --jvm-options="-XX:+UseG1GC -XX:+UseStringDeduplication -XX:InitialRAMPercentage=50.0 -XX:MinRAMPercentage=66.6 -XX:MaxRAMPercentage=66.6 -XX:ActiveProcessorCount=1" \
                  --env SPRING_PROFILES_ACTIVE=passwordless BP_JVM_VERSION=17 \
                  --target-module ${{ env.ADMIN_SERVER_TGT }}

    - name: Deploy customers-service
      uses: azure/CLI@v1
      with:
        azcliversion: ${{ env.AZCLI_VER }}
        inlineScript: |
          az config set extension.use_dynamic_install=yes_without_prompt
          az spring app deploy \
                  --resource-group ${{ secrets.RESOURCE_GROUP }} \
                  --service ${{ secrets.SPRING_APPS_SERVICE_NAME }} \
                  --name ${{ env.CUSTOMERS_SERVICE }} \
                  --source-path ${{ github.workspace }} \
                  --jvm-options="-XX:+UseG1GC -XX:+UseStringDeduplication -XX:InitialRAMPercentage=50.0 -XX:MinRAMPercentage=66.6 -XX:MaxRAMPercentage=66.6 -XX:ActiveProcessorCount=1" \
                  --env SPRING_PROFILES_ACTIVE=passwordless BP_JVM_VERSION=17 \
                  --target-module ${{ env.CUSTOMERS_SERVICE_TGT }}

    - name: Deploy vets-service
      uses: azure/CLI@v1
      with:
        azcliversion: ${{ env.AZCLI_VER }}
        inlineScript: |
          az config set extension.use_dynamic_install=yes_without_prompt
          az spring app deploy \
                  --resource-group ${{ secrets.RESOURCE_GROUP }} \
                  --service ${{ secrets.SPRING_APPS_SERVICE_NAME }} \
                  --name ${{ env.VETS_SERVICE }} \
                  --source-path ${{ github.workspace }} \
                  --jvm-options="-XX:+UseG1GC -XX:+UseStringDeduplication -XX:InitialRAMPercentage=50.0 -XX:MinRAMPercentage=66.6 -XX:MaxRAMPercentage=66.6 -XX:ActiveProcessorCount=1" \
                  --env SPRING_PROFILES_ACTIVE=passwordless BP_JVM_VERSION=17 \
                  --target-module ${{ env.VETS_SERVICE_TGT }}

    - name: Deploy visits-service
      uses: azure/CLI@v1
      with:
        azcliversion: ${{ env.AZCLI_VER }}
        inlineScript: |
          az config set extension.use_dynamic_install=yes_without_prompt
          az spring app deploy \
                  --resource-group ${{ secrets.RESOURCE_GROUP }} \
                  --service ${{ secrets.SPRING_APPS_SERVICE_NAME }} \
                  --name ${{ env.VISITS_SERVICE }} \
                  --source-path ${{ github.workspace }} \
                  --jvm-options="-XX:+UseG1GC -XX:+UseStringDeduplication -XX:InitialRAMPercentage=50.0 -XX:MinRAMPercentage=66.6 -XX:MaxRAMPercentage=66.6 -XX:ActiveProcessorCount=1" \
                  --env SPRING_PROFILES_ACTIVE=passwordless BP_JVM_VERSION=17 \
                  --target-module ${{ env.VISITS_SERVICE_TGT }}

